### PR TITLE
Use `fs.lstatSync` instead of `fs.existsSync` to handle broken symlinks

### LINKED ISSUE #63: Broken symlinks are silently ignored
As the title says, the `trash` function silently ignores broken symlinks (because `fs.existsSync` returns false), whereas https://github.com/sindresorhus/macos-trash handles them as expected, i.e.  moving them to the Trash. Is the former behavior intentional?

### PR DESCRIPTION
**Pull request by jdanford**
Fixes #63

### CODE REVIEW

**Comment by kevva** [comment]
Could you possibly add a test too?

**Comment by jdanford** [comment]
Done!

**Comment by jdanford** [comment]
@kevva @sindresorhus The build is failing on Linux with the following error:
```
Command failed: df -kP /tmp/b80caf87-5ea4-4e54-a35c-f5b1198ca6f8/ccc
df: ‘/tmp/b80caf87-5ea4-4e54-a35c-f5b1198ca6f8/ccc’: No such file or directory
```
Is this more likely an issue with https://github.com/kevva/xdg-trashdir or https://github.com/sindresorhus/df?

**Comment by sindresorhus** [comment]
Would you be able to look into that? I don't have time right now, and I don't think this should land if it breaks the Linux implementation.

**Comment by jdanford** [comment]
I don't want to break anything either – I'll do my best to fix it!

**Comment by jdanford** [comment]
@sindresorhus tests are finally passing on Linux thanks to https://github.com/kevva/xdg-trashdir/pull/5 – is this ready to be merged?

**Pull request merged**
